# Generated by Django 4.0.5 on 2022-06-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('difficulty', models.IntegerField(default=0)),
                ('solved_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='kjxnwek')),
                ('password', models.TextField(verbose_name='buhw')),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adiperiwal_oj.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder', models.TextField(verbose_name='C++')),
                ('useroutput', models.TextField(verbose_name='xyz')),
                ('sub_date', models.DateTimeField(verbose_name='Submitted at')),
                ('verdict', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adiperiwal_oj.problem')),
                ('qwerty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adiperiwal_oj.user')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='y',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adiperiwal_oj.user'),
        ),
    ]
